import React, { useEffect, useState } from 'react';
import { TUIKit } from '@tencentcloud/chat-uikit-react';
import { TUILogin } from '@tencentcloud/tui-core';
import { useLoginStore } from '@stores/index';
import { genTestUserSig } from '@utils/GenerateTestUserSig';
import '@tencentcloud/chat-uikit-react/dist/cjs/index.css';
export default function MessagePage() {
  const [chat, setChat] = useState<any>();
  const { useInfo } = useLoginStore();
  const init = () => {
    // const  = genTestUserSig({
    //   SDKAppID: 1600034770,
    //   userID: useInfo?.nickname,
    //   secretKey: ''
    // })
    const loginInfo: any = {
      SDKAppID: 1600034770, // Your SDKAppID. Get it from Step 4
      userID: 'tester', // Your userID. Get it from Step 5
      useProfanityFilterPlugin: true,
      // UserSig is a cipher for a user to log in to IM. It is the ciphertext generated by encrypting information such as userID. Get it from Step 5
      userSig: 'eJwtjMsKwjAUBf8lW6XmYRJacCGEolgEtWIXbpTclosooQlFEf-d2Lg7ZwbmTerqkA3Qk4LwjJLp*NHCI2CLIw7gQxzJeHu7OIeWFExRSsVca5oMPB32ELmUkkeVaMD7j2mmhVCC838Fuxiuj9q-WrU7lbCtGqrzzQBmCeuG586vzN4wPM*uYVJy3y3I5wuZrTF1', // Your userSig. Get it from Step 5
      useUploadPlugin: true,
    };
    TUILogin.login(loginInfo).then(() => {
      const { chat } = TUILogin.getContext();
      setChat(chat);
    }).catch(() => {});
  }
  useEffect(() => {
    (async ()=>{
      const chat = await init()
      setChat(chat)
    })()
  }, [])


  return (
    <TUIKit chat={chat} language={'en'}></TUIKit> // language support en or zh
  )
}